version: "3.8"

networks:
  corp:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/dashboard/Dockerfile
      args:
        NODE_ENV: "production"
        BUILD_FLAG: ""
    image: api:nx-dev
    ports:
      - 4939:4939
    environment:
      NODE_ENV: "production"
      PORT: 4939
    networks:
      - corp
    restart: on-failure